### ISSUE TITLE
runway 2.6.2 adds --no-color if we run from TTYs

### ISSUE THREAD

**Issue by pbalajiips** [onicagroup/runway#1464]
### Bug Description

--no-color not supported by serverless 3.19.0 but still runway 2.6.2 adds --no-color if we run from TTYs

refer:
 https://github.com/serverless/serverless/issues/11142

### Expected Behavior

by default  --no-color should not be added if shell is tty 

### Steps To Reproduce

Example project: ...

1. use serverless version 3.19.0
2. run "runway deploy" on tty (normal shell it works fine)
...

### Runway version

2.6.2

### Installation Type

npm (npm, yarn, etc)

### OS / Environment

os: amazonlinux2
Python: 3.7
npm version: 7.24.0
serverless version:3.19.0

### Anything else?

n/a

**Comment by pbalajiips** [comment]
For time being i have fixed it by

```
sed -i '/--no-color/d' /usr/local/lib/python3.7/site-packages/runway/module/serverless.py
```

Suggestion: Since serverless not supporting this we can remove permanently.

**Comment by jake-skipper** [comment]
Hello @pbalajiips ,

We were able to reproduce this behavior, and we have just cut a release for Runway 2.6.3 which includes a change to Serverless execution when Runway is running in no color mode, based on the `FORCE_COLOR=0` suggestion from the Serverless devs in your linked issue with them. Hopefully this helps.

As the behavior is now significantly changed, I am going to close this issue now. If you continue to run into problems, feel free to open a new issue with the new details.

Thanks!
