### ISSUE TITLE
incorrect url in quickstart

### ISSUE THREAD

**Issue by zachtuttle** [onicagroup/runway#15]
the link in 
https://github.com/onicagroup/runway/blob/master/quickstarts/runway/README.md 
for cloudformation should link to 

https://github.com/onicagroup/runway/blob/master/quickstarts/runway/runway-quickstart.yml

not 

https://github.com/onicagroup/runway/blob/master/quickstarts/runway-quickstart.yml

**Comment by troyready** [comment]
Thanks @zachtuttle !
