### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by varma-amit** [onicagroup/runway#1986]
**Question**
How to source git repo from runway.yml?
deployments:
  - name: test-deployment
    modules:
      - path: git::git://alm-github.systems.<org>/terraform-google-bigquery.git
        parameters:
          dataset_id: "Testing-runway"
    regions:
      - europe-west2
      
**Context**
I am trying to source terraform module stored in github repo, but when I pass the git link of repo in the "path" attribute of modules section in runway.yml and execute runway plan, it returns error as follows:

$runway plan

return self.__git_ls_remote(self.__determine_git_ls_remote_ref())
  File "/usr/lib/python3.9/site-packages/runway/sources/git.py", line 77, in __git_ls_remote
    ls_remote_output = subprocess.check_output(cmd)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'ls-remote', '', 'HEAD']' returned non-zero exit status 128.
---------------------------------------------------------------------------------------------------------------------------
I am able to clone the repo manually with git clone command on the host machine where runway is installed, and ssh key is also added to github repo.
`git ls-remote <repo_url> HEAD` is also returning output without any error on manual execution on the terminal.
I am assuming it has to do something with ssh authentication.
Can someone please address this asap as it is blocking critical operations in our project.

**Comment by mbordash2** [comment]
Hi @varma-amit , This was addressed with the latest release. You were doing the correct thing but was hitting a code limitation that was addressed.  Please retry and re-open this if you have further issues.
