### ISSUE TITLE
Request: `.flake8` configuration file support

### ISSUE THREAD

**Issue by GarisonLotus** [onicagroup/runway#2]
[Lines 112 - 114 in runway/commands/base.py](https://github.com/onicagroup/runway/blob/master/runway/commands/base.py#L112-L114) are executing a flake8 run during runway preflight specifying `exclude` directives.  Because of this, the .flake8 configuration file I have in the root of my repo is ignored. 

I've verified this at the root of a repo I'm working in by manually executing flake8, both with `--exclude=node_modules,.serverless` and without. When I include the exclude directive, my `.flake8` config file is ignored.

Can we check the filesystem for .flake8 (and maybe the other names flake8 supports) and source them if present? It seems odd we support overriding the yamllint configuration, but not flake8.

**Comment by troyready** [comment]
Thanks @GarisonLotus . Added `.flake8` support in v0.13.0
