### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by speterson-zoll** [onicagroup/runway#226]
**Question**
I am just getting familiar with Runway, and see that it can be used with Terraform.  Are there any plans to make Runway work with Terragrunt?

**Context**
I like the DRY structure I have with Terragrunt, so I thought I'd check.

**Comment by troyready** [comment]
@speterson-zoll it's not currently on the roadmap, as it's not longer part of our best practices for Terraform management. Meant in no way to diminish its historical contribution to the Terraform ecosystem, now we'd instead recommend:

* Using native Terraform modules for DRYness
* Minimizing pre/post-hook usage, and implementing them in cross-platform idempotent python in Runway where needed

I'm going to close the issue for now for record keeping, but open to additional thoughts on it in the future (especially if Terragrunt adds additional features that Hashicorp is unwilling to add upstream).
