### ISSUE TITLE
[BUG] Custom AWS_PROFILE, avoid default profile

### ISSUE THREAD

**Issue by mislavlukach** [onicagroup/runway#255]
**Describe the bug**
Not able to define AWS_PROFILE environment variable properly. I'm trying to set this variable to a value other than `default` and it's not working.

**To Reproduce**
1. Add AWS_PROFILE = custom_profile to your runway.yml
2. Run `runway deploy`

**Expected behavior**
AWS_PROFILE = custom_profile

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Version 10.14.5
- Runway version 1.7.2
- Python version 3.7.7

**Additional context**
My profile is defined both in **~/.aws/credentials** and in **~/.aws/config**
I'm not sure if this is your issue or something related to boto3. 
See also: [https://stackoverflow.com/questions/33297172/boto3-error-botocore-exceptions-nocredentialserror-unable-to-locate-credential](https://stackoverflow.com/questions/33297172/boto3-error-botocore-exceptions-nocredentialserror-unable-to-locate-credential)

**Comment by ITProKyle** [comment]
Are you receiving the same error as what is present in the stackoverlow question? If so and the profile is an AWS SSO profile, the released version of botocore does not support it but we have a patch coming (#251) to support it until the official support is released. 

Ultimately, we arn't doing anything special in regards to loading AWS credentials. The underlying framwork/SDK (Serverless, Terraform, boto3/botocore, etc) being used is responsible for handling that. The only portion that would be on us is getting values into the environment during execution.

Are you seeing an issue in passing any other environment variables to your modules?
