### ISSUE TITLE
[Request] Add a path parameter

### ISSUE THREAD

**Issue by aoggz** [onicagroup/runway#27]
When using runway via a Docker container, it can get tricky to have Runway configurations in a directory different from your source code. It would be nice to have runway accept a path parameter that it would use to search for the `runway.yml` file. 

Then the file paths within the `runway.yml` would still have to be relative to that file.

**Comment by ITProKyle** [comment]
Im not sure I see the advantage of storing the Runway config file anywhere other than the root of the directory containing the modules to be deployed.

Could you provide a more detailed use case preferable with an example repo?

**Comment by aoggz** [comment]
So the original use case that warranted the creation of this issue was as follows:

- A monorepo containing many deployment packages
- A top-level, default `runway.yml` that was the main entrypoint for deployments in our CI/CD pipeline
- Other `runway.yml` files that lived in a directory at the same level of the modules it was configured to deploy

And the problem would arise when I would use my `docker run runway ...` alias instead of the runway CLI directly. I configured it to pull in the current directory, which would exclude the deployment modules in this case. 

All that said, this is not a use case for my team anymore. I'm fine with just closing this issue, if the perceived value is limited.
