### ISSUE TITLE
[BUG] Lookup defaults cannot contain certain characters

### ISSUE THREAD

**Issue by aoggz** [onicagroup/runway#280]
**Describe the bug**
A default string value for a lookup that contains an `=` will cause the lookup resolution to fail

**To Reproduce**
1. Add a lookup with a default value containing a `=`.
2. Run `runway plan` or `runway deploy`

**Expected behavior**
An escape syntax should be provided, or the lookup interpolation should be changed 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version: 10.15.4

**Additional context**
An example of a `runway.yml` file with the issue is:
```
deployments:
  - modules:
      - path: infrastructure
        ...
        parameters:
          broken_var: ${var var_name.${env DEPLOY_ENVIRONMENT}::default=long_value_with_equal_sign_at_end=}
```
The output for this error is below:
```
runway.cfngin.exceptions.FailedVariableLookup: Couldn't resolve lookup in variable `infrastructure.parameters`, lookup: ${Lookup<Literal<'var'> Concatenation[Literal<'var_name.'>, Lookup<aoggz (Literal<'env'> Concatenation[Literal<'DEPLOY_ENVIRONMENT'>])>, Literal<'::default=long_value_with_equal_sign_at_end='>]>}: (<type 'exceptions.ValueError'>) too many values to unpack
```

I was investigating migrating to using the new `parameters` syntax over just using `*`-scoped `env_vars` as we had done in the past (with environment-specific `env_vars` that supercede the `*`-scoped vars). We have been using runway since 2017, so we have some old configuration files that we'd like to update. The wildcarded `env_vars` _works_, it's just not the greatest solution; the behavior of the configuration can be pretty obtuse to fresh eyes. 

**Edit**:
I did forget to mention that I also tried to nest the default value back into the `runway.variables.yml` file:
```
${var var_name.${env DEPLOY_ENVIRONMENT}::default=${var var_name.default}}
```
This lead to a similar error:
```
runway.cfngin.exceptions.FailedVariableLookup: Couldn't resolve lookup in variable `infrastructure.parameters`, lookup: ${Lookup<Literal<'var'> Concatenation[Literal<'var_name.'>, Lookup<aoggz (Literal<'env'> Concatenation[Literal<'DEPLOY_ENVIRONMENT'>])>, Literal<'::default='>, Lookup<long_value_with_equal_sign_at_end= (Literal<'var'> Concatenation[Literal<'var_name.default'>])>, Literal<''>]>}: (<type 'exceptions.ValueError'>) too many values to unpack
```

**Comment by ITProKyle** [comment]
Thanks for reporting this. It should be a pretty easy fix.

Lookup arguments use a very basic parser of `string.split('=')` to convert each argument into a a dict. If we change it to `string.split('=', 1)`, it will split it at the first `=` it finds and leave the remaining value as is.

**Comment by aoggz** [comment]
I've updated to use `v1.8.0`, and this is working as we'd expect. Thanks @troyready & @ITProKyle for the quick turnaround! 🚀
