### ISSUE TITLE
[REQUEST] There should be a “dev” deployment of auth@edge that does not use CloudFront

### ISSUE THREAD

**Issue by ITProKyle** [onicagroup/runway#296]
CloudFront takes forever to update making it a horrible dev experience when making iterative changes while troubleshooting. We should find to retain the full functionally of auth@edge but, without using CloudFront for faster iterations.

**Comment by troyready** [comment]
Since CF distribution management (at least at the lowest price class) isn't the comical wait-forever mess it used to be, I think a stronger case can be made now to drop this in favor of our normal pitch for best practices around environment parity.

**Comment by ITProKyle** [comment]
I am fine with that. The original task this was cloned from was created prior to [CloudFront reducing propagation times](https://aws.amazon.com/blogs/networking-and-content-delivery/slashing-cloudfront-change-propagation-times-in-2020-recent-changes-and-looking-forward/).
