### ISSUE TITLE
Broken link on Docs » Advanced Features » Blueprints

### ISSUE THREAD

**Issue by par-texx** [onicagroup/runway#369]
**Describe the bug**
https://docs.onica.com/projects/runway/en/release/cfngin/blueprints.html has a broken link.

> Making your own should be easy, and you can take a lot of examples from Runway blueprints. In the end, all that is required is that the 

The link that "Runway Blueprints" does not exist.  

![image](https://user-images.githubusercontent.com/8822931/86021102-f5c1f580-b9e5-11ea-8161-323c3eb6da04.png)

![image](https://user-images.githubusercontent.com/8822931/86021130-feb2c700-b9e5-11ea-820e-f817f5cebcd7.png)

**Comment by ITProKyle** [comment]
Thanks. Looks like it didn't get updated after we moved `src/runway/` back to `runway/.
This is the new path: https://github.com/onicagroup/runway/tree/master/runway/blueprints
