### ISSUE TITLE
[REQUEST] serverless.ts Support

### ISSUE THREAD

**Issue by ShaunEdiger** [onicagroup/runway#385]
**Is your feature request related to a problem? Please describe.**
Serverless Framework has updated its templates for typescript projects, which now use `serverless.ts`.

To reproduce:

```zsh
serverless create --template aws-nodejs-typescript
```

You'll see that there is no `serverless.yml` file present.  In lieu of it, there's `serverless.ts`.

**Describe the solution you'd like**
Update Runway to detect and honor the presence of `serverless.ts`.

Change this –

```python
        if (self._is_file('serverless.yml') or self._is_file('serverless.js')) \
```

– to this –

```python
        if (self._is_file('serverless.yml') or self._is_file('serverless.js') or self._is_file('serverless.ts')) \
```

I'm not sure if there will be down-stream effects to handle, but this is where I'd start.

**Describe alternatives you've considered**
None, but I'm open to ideas.

**Additional context**

```zsh
sls --version
Framework Core: 1.75.1
Plugin: 3.6.16
SDK: 2.3.1
Components: 2.32.0
```

**Comment by ITProKyle** [comment]
fyi, file detection is the "last resort" when determining module type. having `.sls` at the end of the module directory and/or explicitly specifying `type: serverless` on the module in the runway config file takes precedence and allows for use of `serverless.ts` with previous versions of runway.
