### ISSUE TITLE
[TODO] investigate implementing a code formatter

### ISSUE THREAD

**Issue by ITProKyle** [onicagroup/runway#397]
# Viable Options

- [autopep](https://github.com/hhatto/autopep8)
- [black](https://github.com/psf/black)
- [yapf](https://github.com/google/yapf)

# Considerations

- Should we implement one?
- Which one should we implement?
- How will it impact the code base?
- How will it impact the developers/maintainers?

**Comment by troyready** [comment]
fwiw, I liked my experience with `black` in another project.

**Comment by ITProKyle** [comment]
I feel the same. I recently worked with it in the [poetry](https://github.com/python-poetry/poetry) repo paired with `pre-commit`.

Given how easy it is to configure compared to the others (since it as practically no configuration) this may be more of `investigate implementing black`.
