### ISSUE TITLE
Binary builds require glibc >= 2.29, breaking compatibility with older linux distros (e.g. Amazon Linux 2)

### ISSUE THREAD

**Issue by troyready** [onicagroup/runway#506]
It appears that GitHub Actions update bumped the glibc version used in binary builds, causing errors like:

```
155] Error loading Python lib '/codebuild/output/src662356390/src/github.com/devmohammedothman/runway-cloudformation/node_modules/@onica/runway/src/runway/libpython3.7m.so.1.0': dlopen: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /codebuild/output/src662356390/src/github.com/devmohammedothman/runway-cloudformation/node_modules/@onica/runway/src/runway/libpython3.7m.so.1.0)
```

Assuming CodeBuild w/ AL2 remains a supported platform, we should find a way to make this work.

**Comment by troyready** [comment]
I can't decide exactly the path I'd like to explore to fix this. My first inclination is to switch the `ubuntu-latest` runner to ubuntu-16.04 (_presumably_ with glibc 2.23). Big downside of that is it would all be require installing a new version of python (e.g. pyenv + [xxenv-latest](https://github.com/momo-lab/xxenv-latest) to pull in the latest 3.7 patch release).

Might just be easier to host a custom docker image; very open to thoughts @ITProKyle

**Comment by ITProKyle** [comment]
@troyready I think the issue is that `ubuntu-latest` as changed to 20.04 LTS.

> Ubuntu-20.04 is ready to be the default version for the “ubuntu-latest” label in GitHub Actions and Azure DevOps. This change will be rolled out over a period of several weeks beginning on November, 30. (December, 22 - January, 4 will be a migration break due to holidays) (https://github.com/actions/virtual-environments/issues/1816)

So, if we change `ubuntu-latest` to `ubuntu-18.04` we should be back to where we were. I think that some of the build/release scripts rely on the value so they may need updated as well.

Will there be any negative future impact to pinning us to `ubuntu-18.04` rather then using 20.04?
