### ISSUE TITLE
[Request] upgrade requirement on boto3 to latest version

### ISSUE THREAD

**Issue by jpelletier1984** [onicagroup/runway#51]
I need to create a custom lookup that uses some new boto3.client('ec2') functionality like describe_transit_gateways. It would be nice if runway shipped with the latest version of boto3 !

**Comment by troyready** [comment]
Noted; it's blocked on a stacker release, I'll ping them about it.

**Comment by troyready** [comment]
@jpelletier1984 v0.45.2 should fix this
