### ISSUE TITLE
[TODO] remove CFNgin profile support

### ISSUE THREAD

**Issue by ITProKyle** [onicagroup/runway#516]
**This is for Runway v2.**

This functionality was inherited from Stacker.

Runway is responsible for credential handling making this config option redundant/obsolete.

**Comment by bensoer** [comment]
Is there documentation on what the alternative / desired setup should be ? Currently this is used at my work as we have scenarios where a single stack within the module needs to be deployed to a different AWS account to work with the current module in the account the module is being deployed to

**Comment by ITProKyle** [comment]
Yes - [`assume_role`](https://docs.onica.com/projects/runway/en/stable/runway_config.html#deployment) is the way that Runway handles AWS credentials. It is set per-deployment so the stack that needs to be deployed into a different account would need to be in its own deployment.
