### ISSUE TITLE
[QUESTION] How to use Terraform outputs as inputs in another module?

### ISSUE THREAD

**Issue by marek-roskowicz** [onicagroup/runway#578]
**Question**
How to use Terraform outputs as inputs in another module?
**Context**
 I can't get the answer straight from documentation. But simple example is: I defined one module and tag it as `networking` where I setup all VPC, subnets, NAT for my AWS account. Then I want to have another module let's called it `instances` where I want to setup all EC2 instances. For that I will need a reference to the VPC and subnets outputs from `networking`  module. How can I get to those outputs from runway? Any options to do that like in Terragrunt with `dependency` and `inputs`
 
That's how my runway.yaml looks like:
![Screenshot 2021-04-23 at 20 13 51](https://user-images.githubusercontent.com/79088011/115913148-21780580-a468-11eb-8933-2ef991c2ff71.png)

And project structure: 
![Screenshot 2021-04-23 at 20 10 32](https://user-images.githubusercontent.com/79088011/115913195-305eb800-a468-11eb-89be-d2a1741de0ca.png)

**Comment by ITProKyle** [comment]
Runway does not pass anything between modules. It also does not have anything built into it capable of getting an output from Terraform. You would need to use something built into the IaC tool you are trying to pass the value to to get the value or use one of the lookups built into Runway to grab the value from SSM or a CloudFormation output (which would require populating SSM or CFN with the value using Terraform).

**Comment by marek-roskowicz** [comment]
So have you got any example of how to structure the Terraform code, so it will possible to use native Terraform outputs to pass information between modules?

**Comment by ITProKyle** [comment]
The only way to use native Terraform outputs would be to treat your `configs/` directory as one Terraform module and have Runway deploy it as one Terraform module. This would require the creation of a `configs/main.tf` file that treats `/configs/iam/`, `configs/instances/` and `configs/networking/` as submodules. `tf-backend/` would also need to be pulled out of `configs/` to avoid any potential file conflicts.

This would make your `runway.yml` look something like this (only showing relevant fields):

```yaml
deployments:
  - name: Terrafrom Backend
    modules:
      - path: tf-backend
  - name: Terrafrom
    modules:
      - path: configs
```

As for examples of the Terraform code, I do not have any examples on hand.

**Comment by marek-roskowicz** [comment]
Thank you very much @ITProKyle, we decided to use SSM as you advice.
