### ISSUE TITLE
[Request] print info message when unknown directives are in the runway.yml

### ISSUE THREAD

**Issue by GarisonLotus** [onicagroup/runway#59]
In an effort to avoid human errors, I suggest that we print warning messages when unknown directives in the yaml config to show that a deployment was potentially incorrectly configured.

The long version of this story:
A user was setting up a runway deployment from scratch that would be executed as that user and assume role into the proper account to perform deployments.  They were running into problems with 403 access denied errors on their initial deployment test.  Being that the 403 was the only error shown, they spent several hours (pulling in other engineers as well) to figure out what was going on and digging into cloudtrail to no avail. unfortunately, the issue was not a 403 access denied on the role being assumed, but an issue with runway not assuming the role.

Eventually, it was noticed that the message `INFO:runway:Assuming role`was not in the output, so there was something wrong with that part of the config.  Turns out human error had a directive of `assume_role` instead of `assume-role` with a cost of around 10 man hours until someone noticed this simple typo.

Can we have Runway print an info message (or warn) stating something like this:

`WARN:runway:Unknown directive found in runway.yml: assume_role. Please check the online documentation for valid values.`

Thanks!

**Comment by ITProKyle** [comment]
this was added in [v1.0.0](https://github.com/onicagroup/runway/blob/master/CHANGELOG.md#100---2019-10-30)
