### ISSUE TITLE
Deployments should be programmatically selectable

### ISSUE THREAD

**Issue by troyready** [onicagroup/runway#68]
Currently deployments can be interactively selected, or selection can be skipped entirely (via the `CI` environment variable).

This makes it impossible to do selective deployments/teardowns on a CI system (without resorting to brittle workarounds like echoing numbers into the runway's stdin).

An alternative to this should be provided. One option would be to allow optional tags to be specified on modules, and add a command line option to restrict operation to matching modules.

**Comment by ITProKyle** [comment]
You mention both deployments and modules here. Are you thinking there be an argument for both to have full cli control or do you think deployments alone would suffice?

```
# both deployments and modules could be treated as: "deployment IN deployments AND module IN modules"
runway (deploy|takeoff) --deployments (<name>|<index>),(<name>|<index>) --modules (<name>|<index>),(<name>|<index>)

# or just deployments
runway (deploy|takeoff) --deployments (<name>|<index>),(<name>|<index>)
```

> allow optional tags to be specified on modules

This is an interesting idea for grouping. The same effect could be achieved through what I mentioned above. While I'm not opposed to adding tags, I think the `--deployments` and `--modules` options may be a more natural introduction. Thoughts?

**Comment by troyready** [comment]
When I was first typing out the issue I really intended to just mention modules (seemed more simple than trying to include deployments too), but then I just went and donked it up.

Upon further reflection, I'm more strongly convinced to just go for a per-module tag system. For most configs with a single deployment, the tag option will function as a module selector. And for more complex multi-deployment configs there will be enough flexibility to accommodate any selection.
