### ISSUE TITLE
[QUESTION] - cfn/xref/rxref Cross Account Functionality in Runway v2.0+

### ISSUE THREAD

**Issue by bensoer** [onicagroup/runway#684]
**Question**
Does cfn/xref/rxref work for cross account lookups in Runway v2.0+ ? Based on documentation, this is not possible, however in older versions (v0.47.1) it was - although not documented at the time ?

Is there a Runway v2.0+ way to solve this ?

**Context**
I am currently upgrading my works runway project. It was built and has been running for the past year using v0.47.1. Our project involves a single "environment" having to deploy to multiple AWS accounts. 

@ITProKyle was able to answer an earlier question related to this (https://github.com/onicagroup/runway/issues/516) with the deprecation of the "profile" attribute within stacks.

My use case is that we setup Route53 DNS records for given root domains within 1 AWS account ( mycompany.com) but then we have NS records within it that route dev subdomains to a 2nd AWS account (dev.mycompany.com) which there then handles all domains underneath it (benlambda1.dev.mycompany.com etc...). To set this up, we have runway deploying CF templates to both environments, but I need to be able to lookup AWS Account 2's NS values so that they can be put into AWS Account 1's Route53

With our old implementation (v0.47.1), xref was able to lookup across accounts and retrieve this information. I am not sure if this is at all because we used the "profile" attribute within the stack, thus leaving it within the same module

Full Disclosure: I have not actually tried/tested cfn/xref cross account on Runway v2.0+ as the conversion is quite a process and documentation seems to say its not possible. Im hoping to find out whether it is possible, and what would be the best practice to solve this

**Comment by ITProKyle** [comment]
There are no built-in lookups that support cross account nor have there ever been (at least not intentionally).

This could be accomplished in a number of different ways with custom hooks/lookups. For example, a lookup that handles changing credentials in a way that fits your auth flow prior to getting the value.

**Comment by bensoer** [comment]
Thanks, @ITProKyle - Further looking at it. Thats probably what was happening haha. Thanks for your help
