### ISSUE TITLE
Ec2SubnetIdList type is wrong

### ISSUE THREAD

**Issue by avosper-intellaegis** [onicagroup/runway#724]
Ec2SubnetIdList type is wrong should be a `List<AWS::EC2::Subnet::Id>` not `List<AWS::EC2::SecurityGroup::Id>`

**To Reproduce**

1. Create a Blueprint leveraging a list of subnet Ids (i.e. blueprint for Rds instance) with variable of type Ec2SubnetIdList:

```
'PriSubnets': {
            'type': EC2SubnetIdList,
            'description': 'The ID of the Private Subnet of the environment.',
        },
```

2. deploy 
3. Check CFN Console
4. Stack is in "RollBack Complete" status with error(s) of Parameter validation failed: parameter value subnet-#### does not exist
5. Check CFN Template, note: 

 ```
"PriSubnets": {
            "Description": "The ID of the Private Subnet of the environment.",
            "Type": "List<AWS::EC2::SecurityGroup::Id>"
        },
```

**Expected behavior**
The Ec2SubnetIdList type to be created in the CFN template as list of subnet ids.

**Desktop (please complete the following information):**

- OS: Windows
- Version 2.0.1,2.1.1

**Additional context**
Add any other context about the problem here. Please provide links to code samples where applicable.

**Comment by ITProKyle** [comment]
Thanks for the bug report.

As a workaround until the fix is released, you can define this class in your project and use it instead of using the one that is configured incorrectly.

```python
from __future__ import annotations

from typing import ClassVar, Literal

from runway.cfngin.blueprints.variables.types import CFNType


class EC2SubnetIdList(CFNType):
    """An array of subnet IDs, such as subnet-123a351e, subnet-456b351e."""

    parameter_type: ClassVar[
        Literal["List<AWS::EC2::SecurityGroup::Id>"]
    ] = "List<AWS::EC2::SecurityGroup::Id>"
```
