### ISSUE TITLE
[Request] Option to reference Terraform backends from SSM parameters

### ISSUE THREAD

**Issue by aoggz** [onicagroup/runway#77]
Similarly to how runway can be configured to use CloudFormation stack outputs via the `terraform_backend_cfn_outputs` property, it would be useful to be able to tell runway to look at SSM parameters for the values of the Terraform backend configuration.

**Comment by troyready** [comment]
Great idea - thanks @aoggz !

Added to master in 92333b42; should make it in a pypi release within the next week

**Comment by aoggz** [comment]
@troyready just checking in. Is a release going to me made soon?

Thanks for your work on this project! It's hugely useful to my team!

**Comment by troyready** [comment]
@aoggz glad to hear it!

We've obviously blown way past our release estimate here (normally cautious to not do smaller merges but _oh well_), so I've cut v0.47.6 so you can use this now.

**Comment by aoggz** [comment]
Thanks @troyready! It's working exactly as expected! :tada: 

Now I have a bunch of `backend[-*].tfvars` files to delete! :smile:
