### ISSUE TITLE
[BUG] cdk: uncaught `subprocess.CalledProcessError` when running `runway plan`

### ISSUE THREAD

**Issue by ITProKyle** [onicagroup/runway#819]
# Bug Description

Runway 2.2.0 change how `cdk diff` was being executed on the backend. Previously, it was being executed by running `subprocess.call()` which does not check the exit code upon completion. As of 2.2.0, `subprocess.check_output()` is being used which raises `subprocess.CalledProcessError` if the exit code is non-zero.

By default, CDK returns a non-zero exit code when running `cdk diff` if a change is detected ([reference issue](https://github.com/aws/aws-cdk/issues/2111)).

https://github.com/onicagroup/runway/blob/a513de035982e1d15bb0e88b54ee9e5e5fcb6ba2/runway/module/cdk.py#L152-L165

# Expected Behavior

Honestly, I am not sure which is the bug. The original implementation that hid the error or the new implementation that does not handle the error. There are arguments for both. The original implementation made it function as all the others function. The new implementation functions as the original tool intends which is to provide more feedback if something changed by returning a non-zero exit code (although our response to this would need some cleanup).

Note, no matter which solution we go with, CDK can be configured to always return a non-zero exit code so that it can function the same as pre-2.2.0. This is explained more in the **Workaround** below.

There are two potential solutions:

1. Revert to the original functionality and completely ignore the exit code that CDK is giving us.
2. Catch the `subprocess.CalledProcessError` and instead use `sys.exit()` to cleanly exit Runway with the same exit code as CDK.

# Workaround

Similar functionality as pre-2.2.0 can be achieved by configuring `cdk diff` to always return a zero exit code (real errors still return a non-zero exit code). This can be accomplished by setting the `context.aws-cdk:enableDiffNoFail` option in the `cdk.json` file as shown below.

```json
{
    "context": {
        "aws-cdk:enableDiffNoFail": true
    }
}
```

**Comment by Sriram-Rackspace** [comment]
For me, Runway 2.2.0 implementation of calling subprocess.check_output() seems better so that when runway plan used in Codepipeline we can decide to got to deploy or not based on the exit code. For runway cloudformation deployments we already do this, i.e. stop the pipeline if there is no change in cloudformation (like someone modifying readme.txt) 
But there needs be way to differentiate from real diff error thats caused because of bad code or dependency issues

**Comment by ITProKyle** [comment]
@Sriram-Rackspace - I am leaning towards solution 2 as well. It provides the most control to the end-user. We will just need to update the docs to include the `aws-cdk:enableDiffNoFail` snippet and why it might be useful to use. From the few things I have read, it sounds like this is now set to `true` be the default when CDK generates a project.

The only drawback with this is that if `aws-cdk:enableDiffNoFail` is not enabled and something changed, `runway plan` will exit immediately and not continue on to the other deployments/modules which could be undesirable. But at least the option of how to handle a diff is placed in the hands of the end-user instead of Runway blindly continuing on like nothing happened.

> But there needs be way to differentiate from real diff error thats caused because of bad code or dependency issues

I don't think there's much Runway can add here without impairing CDK. There would need to be a change in CDK to reliable know this.

With `"aws-cdk:enableDiffNoFail": false`, both a change in diff and a runtime/validation error will return `1`. For Runway to try to understand what `1` means, we would need to capture what CDK is writing to stdout. This would mean that there would be a delay in seeing it's output and it can be formatted differently (e.g. no color). Because it's being captured, there is also a chance it won't be displayed at all (e.g. if Runway encounters an error before outputting it). Once we capture the output, we would then need to parse it to determine if it contains an error. We could check the output for substrings or use regex to find an error. But, because CDK can be used from different languages, there would need to be a lot of conditions to check. There would also be a lot of room for false positives or for things to slip through the cracks. If there was a reliable way to differentiate between these two conditions, I would be all for adding some kind of specialized handling to Runway. But, as of right now, I don't see a reliable way to differentiate between a diff and an error in this situation.

With `"aws-cdk:enableDiffNoFail": true`, a change in diff returns `0` and a runtime/validation error will return `1`. This would allow Runway to continue running through all deployments/modules before exiting if there are no errors. It will also propagate an error from CDK if there is one. While this would not be directly helpful in the use you described, it would at least be able to tell you if there was an error and provide output from all modules that can be inspected for change.
